version: '3.8'

services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: react-vite-ngnix
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./
        target: /app
