version: '3.8'

services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: vite_docker
    ports:
      - "5173:5173"
    volumes:
      - type: bind
        source: ./
        target: /src/portfolio-app
